---
- name: "Installing required dependencies"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip

- name: "Download nomad"
  get_url:
    url: "{{ download_url }}"
    dest: "/tmp/{{ filename }}"
  notify: "restart nomad service"

- name: "Unpacking binary"
  unarchive:
    src: "/tmp/{{ filename }}"
    dest: "/usr/bin"
    remote_src: True

- name: "Creating {{ nomad_user }} group"
  group:
    name: "{{ nomad_group }}"
    state: present

- name: "Creating {{ nomad_user }} user"
  user:
    name: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    state: present

- name: "checking if docker is installed"
  command: "systemctl status docker"
  register: docker_service_status
  ignore_errors: true
  changed_when: false

- name: "Adding {{ nomad_user }} user to docker group"
  user:
    name: "{{ nomad_user }}"
    groups: "docker"
    append: yes
  when: docker_service_status.rc == 0

- name: "Creating config dir"
  file:
    state: directory
    path: "/etc/nomad.d"
    owner: "root"
    group: "root"

- name: "Creating data dir"
  file:
    state: directory
    path: "{{ data_dir }}"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"

- name: "Setting systemd service"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {
        src: "templates/nomad.service",
        dest: "/etc/systemd/system/nomad.service"
      }
    - {
        src: "templates/agent.hcl",
        dest: "/etc/nomad.d/agent.hcl"
      }
  notify: "restart nomad service"

- name: "Enabling service"
  service:
    name: nomad
    enabled: yes
  notify: "restart nomad service"
